### ISSUE TITLE
Asking about one detail about "codeForIntervention.py"

### ISSUE THREAD

**Issue by lili6138** [kyrs/NCC-experiments#2]
Hi kyrs,
Thank you for your great work! There is one detail I am not sure about.
In "codeForIntervention.py", I think "featCasList.append(Num/Den)" should be in the loop of "for index in casldx", and "  featAntiCasList.append(Num/Den)" should be in the loop of "for index in antiCasIdx:". This is one thing I am not sure about. I am looking forward to your reply. Thank you!
 for index in casIdx:
                Num = 0
                Den = 0
                for obF1,origF1 in zip(feat,orignalFeat):
                        Num+=np.abs(obF1[index] - origF1[index])
                        Den+= np.abs(origF1[index])

                featCasList.append(Num/Den)

        ############### calculating for object feature vector #############
        for index in antiCasIdx:
                Num = 0
                Den = 0
                for obF1,origF1 in zip(feat,orignalFeat):
                        Num+=np.abs(obF1[index] - origF1[index])
                        Den+= np.abs(origF1[index])

                featAntiCasList.append(Num/Den)

**Comment by kyrs** [comment]
yes you are right.. thanks for pointing it out. I will make the modification

**Comment by lili6138** [comment]
Ok, thank you very much!
