### ISSUE TITLE
Questions with NCC-datasetGen.py

### ISSUE THREAD

**Issue by siddsuresh97** [kyrs/NCC-experiments#5]
1) Why have you commented out lines 104 and 105. Isn't this what is mentioned in the paper? If not could you explain why you have used 
                                  meanSampStd = np.abs(np.power(meanSampVar,0.5))
				varSampStd  = np.abs(np.power(varSampVar,0.5))

**Comment by kyrs** [comment]
GMM model  which I am using takes std deviation as input rather than variance. If I am not wrong paper talked about sampling variance from uniform distribution. Let me know if I missed something

**Comment by siddsuresh97** [comment]
Oh okay. Yes that's correct! Thanks.

I have tried training the NCC using the data generated from this code. I got an accuracy of 52% and 62% on the Tuebingen dataset. I was wondering if you remember how much you were getting. 
While trying to select the causal and anti-causal features, the trained NCC gave a score of 1 for each of the features. Do you know why this could be happening and how I can resolve it?

**Comment by whz789** [comment]
when can you push the whole code?

**Comment by kyrs** [comment]
sorry I am not pursuing the development of the code any longer.  I will try to push whatever I have ... although I wasn't able to replicate the result of the authors.
