### ISSUE TITLE
Realize it in pytorch

### ISSUE THREAD

**Issue by ZhenglinZhou** [kyrs/NCC-experiments#6]
Hi, it is a great job!
This day, I am realizing it in pytorch (https://github.com/zzl-pointcloud/NCC-pytorch). I worked it in 2 steps: finish the NCC and then the NCC-ResNet50. 
I test my NCC in tub datasets and get 74% acc, as well as NCC-ResNet50 in VOC classification task and get 93% acc, which is 79% and 97% in this tf version. 
But when I connect them to realize the result in this paper, I get wrong result in Context-features. And this is really confused me.

Could you give me some advice?

**Comment by kyrs** [comment]
Hello,
sorry for replying late, I have checked your repo, its really a nice work.
Unfortunately, I also got similar result when I tried to replicate the results. I have attached the results of my experiment in the thread. 
 Currently, I am not pursuing the given line of research in details but if you want more input about this then you can talk to @siddsuresh97, he might be better suited to answer your questions. 
One of the conclusion of our discussion was that, it could be a problem of out of distribution data, especially for such a weak signal. But nothing concrete. 
Thanks again. 
![context](https://user-images.githubusercontent.com/10322195/95473965-3bf20200-09a2-11eb-8094-adf28f6c7f4f.png)
![object](https://user-images.githubusercontent.com/10322195/95473987-401e1f80-09a2-11eb-937f-f803bfca6ff7.png)

**Comment by ZhenglinZhou** [comment]
Thanks for your great suggestion!
I will check my code, and try to adjust the paras. It's really help me!
